### ISSUE TITLE
update elasticsearch to 5.5.2

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/container-elasticsearch#4]
we rely on [this](https://github.com/fabric8io/elasticsearch-cloud-kubernetes) in our [dockerfile](https://github.com/samsung-cnct/container-elasticsearch/blob/master/Dockerfile#L17) and it has been bumped to 5.5.2. we are currently running 5.4.2. This will mean a corresponding change in Kibana as well, as these versions must be identical.

**Comment by leahnp** [comment]
@DStorck I have been testing kibana and elasticsearch with `v5.6.3` is it OK to update to that version or should it be 5.5.2 exactly?
