### ISSUE TITLE
Performance enhancements - memory_lock

### ISSUE THREAD

**Issue by gdmello** [samsung-cnct/container-elasticsearch#8]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST
Would like to see support for enabling [`bootstrap.memory_lock`](https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-configuration-memory.html#mlockall)

I've got this working [here](https://github.com/samsung-cnct/container-elasticsearch/compare/master...gdmello:support-mlockall). If there is support/ interest for this feature I could submit a PR. Do let me know.

**Comment by coffeepac** [comment]
A PR would be great!  This is great for ES.

**Comment by gdmello** [comment]
@coffeepac - awesome! opened #9.

**Comment by gdmello** [comment]
This also requires an update to the kubernetes chart - I'll open a PR for that change as well.
